# Generated by Django 3.2.8 on 2021-10-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('price', models.CharField(max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('unpaid', models.BooleanField(default=False)),
                ('due', models.CharField(max_length=200)),
            ],
        ),
    ]
