# Generated by Django 3.2.8 on 2021-10-06 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='unpaid',
        ),
    ]
