# Generated by Django 3.2.8 on 2021-10-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_remove_invoice_unpaid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='email',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='price',
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='paid', max_length=20),
            preserve_default=False,
        ),
    ]
