# Generated by Django 3.2.8 on 2021-10-07 14:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_invoice_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 7, 14, 55, 20, 130162, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
